import { Incident } from '../types/incident';

export const INITIAL_MOCK_INCIDENTS: Incident[] = [
  // CHAIN 1: Financial Database Exfiltration Attack Chain (Highest priority multi-stage attack)
  {
    id: 'INC-1023',
    title: 'Anomalous Bulk Data Exfiltration to Suspicious External IP',
    type: 'Data Exfiltration',
    description: '14.8 GB of encrypted SQL dumps transferred from Finance-DB-01 to external bulletproof host 198.51.100.77 over port 443 during non-business hours.',
    factors: {
      severity: 9.8,
      businessImpact: 9.6,
      assetImportance: 9.5,
      dataSensitivity: 9.8,
      attackConfidence: 9.4,
      affectedUsers: 8.5,
      correlationScore: 9.5,
    },
    weightedScore: 0,
    priorityScore: 0,
    riskLevel: 'CRITICAL',
    sourceIp: '198.51.100.77',
    destinationIp: '10.0.4.15',
    asset: 'Finance-DB-Prod-01',
    assetTier: 'Tier 0 - Crown Jewels',
    user: 'svc_fin_admin',
    userRole: 'Finance Database Service Principal',
    device: 'srv-db-cluster-east',
    mitreId: 'T1041',
    mitreTechnique: 'Exfiltration Over C2 Channel',
    mitreTactic: 'Exfiltration',
    timestamp: '2026-09-01T06:45:00Z',
    correlatedIncidentIds: ['INC-1027', 'INC-1019', 'INC-1012'],
    status: 'NEW',
    recommendedActions: [
      'Immediately isolate Finance-DB-Prod-01 network interface',
      'Block destination egress IP 198.51.100.77 on perimeter firewalls',
      'Revoke service principal credentials for svc_fin_admin',
      'Initiate emergency data breach forensic snapshot and legal notification',
    ],
  },
  {
    id: 'INC-1027',
    title: 'Unauthorized Privilege Escalation to Domain Enterprise Admin',
    type: 'Privilege Escalation',
    description: 'Suspicious token impersonation detected via CVE-2024-49113 exploiting Print Spooler on primary Domain Controller by user01.',
    factors: {
      severity: 9.2,
      businessImpact: 9.4,
      assetImportance: 9.8,
      dataSensitivity: 9.0,
      attackConfidence: 9.0,
      affectedUsers: 8.0,
      correlationScore: 9.0,
    },
    weightedScore: 0,
    priorityScore: 0,
    riskLevel: 'CRITICAL',
    sourceIp: '198.51.100.77',
    destinationIp: '10.0.1.5',
    asset: 'HQ-DC-Primary-01',
    assetTier: 'Tier 0 - Crown Jewels',
    user: 'user01',
    userRole: 'Enterprise Administrator (Elevated)',
    device: 'hq-dc-01.corp.internal',
    mitreId: 'T1068',
    mitreTechnique: 'Exploitation for Privilege Escalation',
    mitreTactic: 'Privilege Escalation',
    timestamp: '2026-09-01T06:30:00Z',
    correlatedIncidentIds: ['INC-1023', 'INC-1019', 'INC-1012'],
    status: 'INVESTIGATING',
    recommendedActions: [
      'Isolate Domain Controller HQ-DC-Primary-01 from mesh peers',
      'Reset all Kerberos KRBTGT account keys',
      'Force global MFA re-authentication for all Tier 0 administrators',
      'Review Active Directory replication logs for DCSync anomalies',
    ],
  },
  {
    id: 'INC-1019',
    title: 'Obfuscated PowerShell Execution with AMSI Bypass',
    type: 'Suspicious PowerShell',
    description: 'Base64 encoded payload executed in memory via powershell.exe invoking Invoke-Mimikatz against LSASS process memory.',
    factors: {
      severity: 8.8,
      businessImpact: 8.5,
      assetImportance: 8.0,
      dataSensitivity: 7.8,
      attackConfidence: 9.2,
      affectedUsers: 6.0,
      correlationScore: 8.5,
    },
    weightedScore: 0,
    priorityScore: 0,
    riskLevel: 'HIGH',
    sourceIp: '198.51.100.77',
    destinationIp: '10.0.2.88',
    asset: 'AppServer-Finance-East',
    assetTier: 'Tier 1 - Mission Critical',
    user: 'user01',
    userRole: 'Senior Financial Analyst',
    device: 'app-fin-node-02',
    mitreId: 'T1059.001',
    mitreTechnique: 'Command and Scripting Interpreter: PowerShell',
    mitreTactic: 'Execution',
    timestamp: '2026-09-01T06:15:00Z',
    correlatedIncidentIds: ['INC-1023', 'INC-1027', 'INC-1012'],
    status: 'INVESTIGATING',
    recommendedActions: [
      'Terminate rogue PowerShell PID 4820 and quarantine parent process',
      'Collect volatile RAM dump from AppServer-Finance-East',
      'Block outbound beaconing on internal subnet',
    ],
  },
  {
    id: 'INC-1012',
    title: 'Distributed Brute-Force Password Spraying Attack',
    type: 'Brute-Force Attack',
    description: 'Over 850 authentication attempts against single sign-on portal targeting corporate accounting accounts within 10 minutes.',
    factors: {
      severity: 7.5,
      businessImpact: 7.2,
      assetImportance: 8.2,
      dataSensitivity: 7.0,
      attackConfidence: 8.8,
      affectedUsers: 8.5,
      correlationScore: 8.0,
    },
    weightedScore: 0,
    priorityScore: 0,
    riskLevel: 'HIGH',
    sourceIp: '198.51.100.77',
    destinationIp: '10.0.0.10',
    asset: 'Okta-IDP-Gateway',
    assetTier: 'Tier 1 - Mission Critical',
    user: 'user01',
    userRole: 'Senior Financial Analyst',
    device: 'gateway-auth-proxy',
    mitreId: 'T1110.003',
    mitreTechnique: 'Brute Force: Password Spraying',
    mitreTactic: 'Credential Access',
    timestamp: '2026-09-01T05:50:00Z',
    correlatedIncidentIds: ['INC-1023', 'INC-1027', 'INC-1019'],
    status: 'INVESTIGATING',
    recommendedActions: [
      'Enable step-up FIDO2 hardware MFA requirement',
      'Apply dynamic rate limiting and geographic IP geofencing on auth gateway',
      'Audit successful logins that succeeded spraying window',
    ],
  },

  // CHAIN 2: Healthcare Ransomware Outbreak (Patient Records Target)
  {
    id: 'INC-1045',
    title: 'Widespread High-Speed File Encryption (Ransomware Activity)',
    type: 'Ransomware Activity',
    description: 'Mass file renaming with .locked extension detected on Patient Records SAN Storage; ransom note dropped in 40+ directory shares.',
    factors: {
      severity: 9.9,
      businessImpact: 9.8,
      assetImportance: 9.6,
      dataSensitivity: 9.5,
      attackConfidence: 9.8,
      affectedUsers: 9.0,
      correlationScore: 9.2,
    },
    weightedScore: 0,
    priorityScore: 0,
    riskLevel: 'CRITICAL',
    sourceIp: '185.220.101.5',
    destinationIp: '10.20.5.50',
    asset: 'EHR-Clinical-Storage-01',
    assetTier: 'Tier 0 - Crown Jewels',
    user: 'dr_miller',
    userRole: 'Chief of Medicine',
    device: 'san-ehr-cluster-01',
    mitreId: 'T1486',
    mitreTechnique: 'Data Encrypted for Impact',
    mitreTactic: 'Impact',
    timestamp: '2026-09-01T06:50:00Z',
    correlatedIncidentIds: ['INC-1039', 'INC-1031'],
    status: 'NEW',
    recommendedActions: [
      'Trigger Emergency Air-Gap on Clinical Storage SAN',
      'Halt shadow copy deletion processes immediately',
      'Verify integrity of immutable offline backups',
      'Notify Hospital Executive Incident Management Team',
    ],
  },
  {
    id: 'INC-1039',
    title: 'Cobalt Strike Beacon Ingress & C2 Lateral Communication',
    type: 'C2 Communication',
    description: 'Malleable C2 HTTP traffic pattern detected periodically transmitting encrypted telemetry to external host 185.220.101.5.',
    factors: {
      severity: 8.6,
      businessImpact: 8.2,
      assetImportance: 8.5,
      dataSensitivity: 8.0,
      attackConfidence: 9.0,
      affectedUsers: 5.5,
      correlationScore: 8.8,
    },
    weightedScore: 0,
    priorityScore: 0,
    riskLevel: 'HIGH',
    sourceIp: '185.220.101.5',
    destinationIp: '10.20.1.14',
    asset: 'MedRecords-AppSrv-03',
    assetTier: 'Tier 1 - Mission Critical',
    user: 'dr_miller',
    userRole: 'Chief of Medicine',
    device: 'ws-er-clinician-14',
    mitreId: 'T1071.001',
    mitreTechnique: 'Application Layer Protocol: Web Protocols',
    mitreTactic: 'Command and Control',
    timestamp: '2026-09-01T06:20:00Z',
    correlatedIncidentIds: ['INC-1045', 'INC-1031'],
    status: 'INVESTIGATING',
    recommendedActions: [
      'Blackhole C2 DNS domain and block destination IP 185.220.101.5',
      'Isolate endpoint ws-er-clinician-14 from medical LAN',
      'Extract memory strings for campaign attribution',
    ],
  },
  {
    id: 'INC-1031',
    title: 'Spearphishing Email with Weaponized Macro Attachment',
    type: 'Suspicious Email / Phishing',
    description: 'Targeted email received with subject "URGENT: Revised Clinical Protocol 2026.docm" containing VBA macro dropper.',
    factors: {
      severity: 7.8,
      businessImpact: 7.0,
      assetImportance: 7.5,
      dataSensitivity: 7.2,
      attackConfidence: 8.6,
      affectedUsers: 4.0,
      correlationScore: 8.2,
    },
    weightedScore: 0,
    priorityScore: 0,
    riskLevel: 'HIGH',
    sourceIp: '185.220.101.5',
    destinationIp: '10.20.1.14',
    asset: 'Workstation-Med-14',
    assetTier: 'Tier 2 - Business Operations',
    user: 'dr_miller',
    userRole: 'Chief of Medicine',
    device: 'ws-er-clinician-14',
    mitreId: 'T1566',
    mitreTechnique: 'Phishing: Spearphishing Link',
    mitreTactic: 'Initial Access',
    timestamp: '2026-09-01T05:30:00Z',
    correlatedIncidentIds: ['INC-1045', 'INC-1039'],
    status: 'INVESTIGATING',
    recommendedActions: [
      'Purge phishing message from all recipient mailboxes across tenant',
      'Block sender domain and malicious attachment SHA256 hashes',
      'Conduct mailbox audit for other clinician interactions',
    ],
  },

  // CHAIN 3: Cloud Infrastructure Takeover / Impossible Travel
  {
    id: 'INC-1052',
    title: 'Impossible Travel & Concurrent Multi-Region AWS Session',
    type: 'Impossible Travel Login',
    description: 'User devops_lead logged into AWS Production Console from Frankfurt (IP 91.240.118.2) 8 minutes after active login from San Francisco.',
    factors: {
      severity: 8.4,
      businessImpact: 8.8,
      assetImportance: 9.0,
      dataSensitivity: 8.5,
      attackConfidence: 9.1,
      affectedUsers: 7.0,
      correlationScore: 7.8,
    },
    weightedScore: 0,
    priorityScore: 0,
    riskLevel: 'HIGH',
    sourceIp: '91.240.118.2',
    destinationIp: '172.31.0.1',
    asset: 'AWS-Prod-Master-Account',
    assetTier: 'Tier 0 - Crown Jewels',
    user: 'devops_lead',
    userRole: 'Lead Cloud Infrastructure Architect',
    device: 'macbook-pro-m3-corp',
    mitreId: 'T1078.004',
    mitreTechnique: 'Valid Accounts: Cloud Accounts',
    mitreTactic: 'Initial Access',
    timestamp: '2026-09-01T06:40:00Z',
    correlatedIncidentIds: ['INC-1058'],
    status: 'NEW',
    recommendedActions: [
      'Revoke active AWS STS tokens and IAM sessions for devops_lead',
      'Enforce password rotation and hardware token validation',
      'Audit AWS CloudTrail events for unauthorized IAM role creation',
    ],
  },
  {
    id: 'INC-1058',
    title: 'Automated IAM Privilege Boundary Modification',
    type: 'Privilege Escalation',
    description: 'CloudTrail detected AttachUserPolicy action granting AdministratorAccess to temporary test user via rogue session.',
    factors: {
      severity: 8.9,
      businessImpact: 9.1,
      assetImportance: 9.2,
      dataSensitivity: 8.8,
      attackConfidence: 9.3,
      affectedUsers: 6.5,
      correlationScore: 8.0,
    },
    weightedScore: 0,
    priorityScore: 0,
    riskLevel: 'CRITICAL',
    sourceIp: '91.240.118.2',
    destinationIp: '172.31.0.1',
    asset: 'AWS-Prod-Master-Account',
    assetTier: 'Tier 0 - Crown Jewels',
    user: 'devops_lead',
    userRole: 'Lead Cloud Infrastructure Architect',
    device: 'macbook-pro-m3-corp',
    mitreId: 'T1068',
    mitreTechnique: 'Exploitation for Privilege Escalation',
    mitreTactic: 'Privilege Escalation',
    timestamp: '2026-09-01T06:48:00Z',
    correlatedIncidentIds: ['INC-1052'],
    status: 'NEW',
    recommendedActions: [
      'Detach AdministratorAccess policy and delete unauthorized IAM principals',
      'Lock AWS Root account and inspect SCP security policies',
    ],
  },

  // STANDALONE / LOWER SEVERITY ALERTS (For realistic noise and comparison)
  {
    id: 'INC-1064',
    title: 'Repeated Failed SSH Login Attempts (Public Bastion)',
    type: 'Failed Login Attempts',
    description: '14 consecutive failed root SSH attempts from 203.0.113.88 against public jumpbox. IP automatically blocked by fail2ban.',
    factors: {
      severity: 4.5,
      businessImpact: 3.2,
      assetImportance: 5.0,
      dataSensitivity: 3.0,
      attackConfidence: 7.5,
      affectedUsers: 1.0,
      correlationScore: 1.0,
    },
    weightedScore: 0,
    priorityScore: 0,
    riskLevel: 'LOW',
    sourceIp: '203.0.113.88',
    destinationIp: '10.0.100.5',
    asset: 'DMZ-Bastion-Linux-01',
    assetTier: 'Tier 3 - General Endpoint',
    user: 'root',
    userRole: 'System Account',
    device: 'bastion-ext-01',
    mitreId: 'T1110.001',
    mitreTechnique: 'Brute Force: Password Guessing',
    mitreTactic: 'Credential Access',
    timestamp: '2026-09-01T06:05:00Z',
    correlatedIncidentIds: [],
    status: 'MITIGATED',
    recommendedActions: [
      'Confirm fail2ban iptables block rule is active',
      'Verify root password authentication remains disabled via SSH config',
    ],
  },
  {
    id: 'INC-1068',
    title: 'Automated Port Scan on Perimeter Edge Router',
    type: 'Port Scan & Recon',
    description: 'SYN packets scanning ports 1-1024 detected by perimeter IDS from external scanning IP 198.18.0.42.',
    factors: {
      severity: 3.8,
      businessImpact: 2.5,
      assetImportance: 6.0,
      dataSensitivity: 2.0,
      attackConfidence: 8.0,
      affectedUsers: 1.0,
      correlationScore: 1.0,
    },
    weightedScore: 0,
    priorityScore: 0,
    riskLevel: 'LOW',
    sourceIp: '198.18.0.42',
    destinationIp: '198.51.100.1',
    asset: 'Edge-Gateway-PaloAlto',
    assetTier: 'Tier 2 - Business Operations',
    user: 'Unknown',
    userRole: 'Unauthenticated External Probe',
    device: 'fw-edge-cluster',
    mitreId: 'T1046',
    mitreTechnique: 'Network Service Discovery',
    mitreTactic: 'Discovery',
    timestamp: '2026-09-01T05:15:00Z',
    correlatedIncidentIds: [],
    status: 'SUPPRESSED',
    recommendedActions: [
      'Standard automated scan ingestion - no manual action required',
      'Confirm edge firewall drop policy is operational',
    ],
  },
  {
    id: 'INC-1072',
    title: 'Adware / Potentially Unwanted Program (PUP) on Marketing Laptop',
    type: 'Malware Detection',
    description: 'Windows Defender quarantined search-bar extension helper in Chrome profile directory of workstation WS-MKT-09.',
    factors: {
      severity: 4.2,
      businessImpact: 3.0,
      assetImportance: 4.0,
      dataSensitivity: 3.5,
      attackConfidence: 8.5,
      affectedUsers: 1.0,
      correlationScore: 1.0,
    },
    weightedScore: 0,
    priorityScore: 0,
    riskLevel: 'LOW',
    sourceIp: '10.0.50.22',
    destinationIp: '142.250.190.46',
    asset: 'Workstation-Mkt-09',
    assetTier: 'Tier 3 - General Endpoint',
    user: 'sarah_marketing',
    userRole: 'Marketing Specialist',
    device: 'ws-mkt-dell-09',
    mitreId: 'T1204.002',
    mitreTechnique: 'User Execution: Malicious File',
    mitreTactic: 'Execution',
    timestamp: '2026-09-01T04:40:00Z',
    correlatedIncidentIds: [],
    status: 'MITIGATED',
    recommendedActions: [
      'Automated quarantine successful - review browser extensions policy',
    ],
  },
  {
    id: 'INC-1075',
    title: 'Suspicious Kerberoasting Activity Against Service Accounts',
    type: 'Lateral Movement',
    description: 'Excessive TGS ticket requests with RC4 encryption requested for SPNs belonging to Microsoft SQL Service accounts.',
    factors: {
      severity: 7.9,
      businessImpact: 7.5,
      assetImportance: 8.5,
      dataSensitivity: 7.8,
      attackConfidence: 8.7,
      affectedUsers: 5.0,
      correlationScore: 6.5,
    },
    weightedScore: 0,
    priorityScore: 0,
    riskLevel: 'HIGH',
    sourceIp: '10.0.3.44',
    destinationIp: '10.0.1.5',
    asset: 'HQ-DC-Primary-01',
    assetTier: 'Tier 0 - Crown Jewels',
    user: 'alex_consultant',
    userRole: 'Contract IT Consultant',
    device: 'laptop-guest-44',
    mitreId: 'T1021.002',
    mitreTechnique: 'Remote Services: SMB/Windows Admin Shares',
    mitreTactic: 'Lateral Movement',
    timestamp: '2026-09-01T06:10:00Z',
    correlatedIncidentIds: [],
    status: 'INVESTIGATING',
    recommendedActions: [
      'Upgrade service account encryption to AES-256 and enforce 25+ character passwords',
      'Disable RC4 encryption support on Kerberos realm',
      'Quarantine endpoint laptop-guest-44 on guest VLAN',
    ],
  },
  {
    id: 'INC-1080',
    title: 'Unusual SMB Lateral Sweep Across Developer Subnet',
    type: 'Lateral Movement',
    description: 'Endpoint 10.0.8.99 initiating rapid SMB connection attempts on TCP 445 across 254 subnet hosts using PsExec artifacts.',
    factors: {
      severity: 8.1,
      businessImpact: 7.6,
      assetImportance: 7.2,
      dataSensitivity: 7.0,
      attackConfidence: 8.8,
      affectedUsers: 6.0,
      correlationScore: 7.0,
    },
    weightedScore: 0,
    priorityScore: 0,
    riskLevel: 'HIGH',
    sourceIp: '10.0.8.99',
    destinationIp: '10.0.8.0/24',
    asset: 'Subnet-Dev-Core',
    assetTier: 'Tier 2 - Business Operations',
    user: 'alex_consultant',
    userRole: 'Contract IT Consultant',
    device: 'laptop-guest-44',
    mitreId: 'T1021.002',
    mitreTechnique: 'Remote Services: SMB/Windows Admin Shares',
    mitreTactic: 'Lateral Movement',
    timestamp: '2026-09-01T06:25:00Z',
    correlatedIncidentIds: ['INC-1075'],
    status: 'INVESTIGATING',
    recommendedActions: [
      'Block TCP port 445 inter-workstation communication with micro-segmentation',
      'Revoke network access credentials for alex_consultant',
    ],
  },
  {
    id: 'INC-1085',
    title: 'Suspicious Cloud Storage Bucket Public Access Enabled',
    type: 'Data Exfiltration',
    description: 'AWS S3 bucket `corp-customer-pii-backup` ACL modified from private to public read by compromised API key.',
    factors: {
      severity: 8.7,
      businessImpact: 9.0,
      assetImportance: 8.9,
      dataSensitivity: 9.4,
      attackConfidence: 9.2,
      affectedUsers: 7.5,
      correlationScore: 6.0,
    },
    weightedScore: 0,
    priorityScore: 0,
    riskLevel: 'CRITICAL',
    sourceIp: '104.244.42.1',
    destinationIp: '172.31.0.1',
    asset: 'S3-Customer-PII-Vault',
    assetTier: 'Tier 0 - Crown Jewels',
    user: 'api_backup_worker',
    userRole: 'Cloud Backup Service Account',
    device: 'aws-s3-service',
    mitreId: 'T1041',
    mitreTechnique: 'Exfiltration Over C2 Channel',
    mitreTactic: 'Exfiltration',
    timestamp: '2026-09-01T06:35:00Z',
    correlatedIncidentIds: [],
    status: 'NEW',
    recommendedActions: [
      'Enable S3 Block Public Access at the AWS account level immediately',
      'Audit S3 server access logs for unauthorized object downloads',
      'Rotate AWS IAM Access Key AKIA...',
    ],
  },
];

/**
 * 25-30 Batch alert generator containing intertwined enterprise incidents
 */
export function generateBatchAlerts(): Incident[] {
  const categories: Incident['type'][] = [
    'Data Exfiltration',
    'Privilege Escalation',
    'Ransomware Activity',
    'Malware Detection',
    'Brute-Force Attack',
    'Failed Login Attempts',
    'Suspicious PowerShell',
    'Impossible Travel Login',
    'Suspicious Email / Phishing',
    'Port Scan & Recon',
    'C2 Communication',
    'Lateral Movement',
  ];

  const assets = [
    { name: 'Core-Banking-DB-01', tier: 'Tier 0 - Crown Jewels' as const, dataSens: 9.8, imp: 9.7 },
    { name: 'ActiveDirectory-DC01', tier: 'Tier 0 - Crown Jewels' as const, dataSens: 9.2, imp: 9.8 },
    { name: 'Customer-Vault-S3', tier: 'Tier 0 - Crown Jewels' as const, dataSens: 9.6, imp: 9.4 },
    { name: 'HR-Payroll-Server-02', tier: 'Tier 1 - Mission Critical' as const, dataSens: 8.8, imp: 8.5 },
    { name: 'EHR-HealthRecords-01', tier: 'Tier 0 - Crown Jewels' as const, dataSens: 9.9, imp: 9.6 },
    { name: 'ERP-SAP-Production', tier: 'Tier 1 - Mission Critical' as const, dataSens: 8.5, imp: 8.7 },
    { name: 'Okta-IDP-Gateway', tier: 'Tier 1 - Mission Critical' as const, dataSens: 8.0, imp: 8.8 },
    { name: 'DMZ-Bastion-Linux-01', tier: 'Tier 3 - General Endpoint' as const, dataSens: 4.0, imp: 5.5 },
    { name: 'Workstation-Fin-22', tier: 'Tier 2 - Business Operations' as const, dataSens: 6.5, imp: 6.0 },
    { name: 'Workstation-Dev-04', tier: 'Tier 2 - Business Operations' as const, dataSens: 5.5, imp: 5.8 },
  ];

  const users = [
    { name: 'admin_jdoe', role: 'Enterprise Administrator' },
    { name: 'svc_database_sync', role: 'Database Sync Daemon' },
    { name: 'sarah_cfo', role: 'Chief Financial Officer' },
    { name: 'dr_miller', role: 'Chief of Surgery' },
    { name: 'dev_alovelace', role: 'Principal Software Engineer' },
    { name: 'hr_manager', role: 'Human Resources Lead' },
    { name: 'contractor_bob', role: 'Third-Party DevOps' },
  ];

  const attackIpClusters = [
    '198.51.100.77', // APT cluster 1
    '185.220.101.5',  // Ransomware cluster 2
    '91.240.118.2',   // Cloud pivot cluster 3
    '45.33.32.156',   // Phishing cluster 4
    '194.26.29.112',  // C2 cluster 5
  ];

  const alerts: Incident[] = [...INITIAL_MOCK_INCIDENTS];
  const countToGenerate = 18;

  for (let i = 1; i <= countToGenerate; i++) {
    const idNum = 1100 + i;
    const cat = categories[Math.floor(Math.random() * categories.length)];
    const assetObj = assets[Math.floor(Math.random() * assets.length)];
    const userObj = users[Math.floor(Math.random() * users.length)];
    // Reuse IP clusters to create strong automatic correlation
    const srcIp = Math.random() > 0.4 
      ? attackIpClusters[Math.floor(Math.random() * attackIpClusters.length)]
      : `203.0.113.${10 + i}`;

    const sev = Math.round((4 + Math.random() * 5.8) * 10) / 10;
    const busImp = Math.round((assetObj.imp * 0.8 + Math.random() * 2) * 10) / 10;
    const conf = Math.round((6.5 + Math.random() * 3.3) * 10) / 10;
    const affUsers = Math.round((2 + Math.random() * 7.5) * 10) / 10;

    const minsAgo = Math.floor(Math.random() * 120);
    const date = new Date(Date.now() - minsAgo * 60000);

    alerts.push({
      id: `INC-${idNum}`,
      title: `${cat} Detected on ${assetObj.name}`,
      type: cat,
      description: `Security sensor triggered high-velocity alert for ${cat} involving identity ${userObj.name} and host ${assetObj.name}.`,
      factors: {
        severity: sev,
        businessImpact: Math.min(10, busImp),
        assetImportance: assetObj.imp,
        dataSensitivity: assetObj.dataSens,
        attackConfidence: conf,
        affectedUsers: affUsers,
        correlationScore: 1.0, // Computed dynamically by correlation engine
      },
      weightedScore: 0,
      priorityScore: 0,
      riskLevel: 'MEDIUM',
      sourceIp: srcIp,
      destinationIp: `10.0.${Math.floor(Math.random() * 10)}.${Math.floor(Math.random() * 250)}`,
      asset: assetObj.name,
      assetTier: assetObj.tier,
      user: userObj.name,
      userRole: userObj.role,
      device: `host-${assetObj.name.toLowerCase()}`,
      timestamp: date.toISOString(),
      correlatedIncidentIds: [],
      status: 'NEW',
      recommendedActions: [
        `Initiate endpoint forensic sweep on ${assetObj.name}`,
        `Validate authentication tokens for user ${userObj.name}`,
        `Inspect network perimeter logs for source IP ${srcIp}`,
      ],
    });
  }

  return alerts;
}

/**
 * Generates a realistic dynamic real-time event for Live SOC Mode
 */
export function generateLiveIncomingAlert(existingAlerts: Incident[]): Incident {
  const nextId = 1200 + Math.floor(Math.random() * 800);
  const highImpactTypes: Incident['type'][] = [
    'Data Exfiltration',
    'Privilege Escalation',
    'Ransomware Activity',
    'Suspicious PowerShell',
    'Impossible Travel Login',
  ];

  const type = highImpactTypes[Math.floor(Math.random() * highImpactTypes.length)];
  
  // Pick an existing incident to establish real-time correlation
  const targetToCorrelate = existingAlerts[Math.floor(Math.random() * Math.min(6, existingAlerts.length))];
  
  const srcIp = targetToCorrelate?.sourceIp || '198.51.100.77';
  const user = targetToCorrelate?.user || 'admin_jdoe';
  const asset = targetToCorrelate?.asset || 'Finance-DB-Prod-01';

  return {
    id: `INC-${nextId}`,
    title: `🚨 LIVE INTRUSION: ${type} targeting ${asset}`,
    type,
    description: `Real-time sensor alert: Detected active ${type} execution matching known APT signature. Shared source IP ${srcIp} and identity ${user}.`,
    factors: {
      severity: Math.round((8.5 + Math.random() * 1.4) * 10) / 10,
      businessImpact: Math.round((8.8 + Math.random() * 1.1) * 10) / 10,
      assetImportance: 9.5,
      dataSensitivity: 9.6,
      attackConfidence: 9.7,
      affectedUsers: 8.0,
      correlationScore: 9.0,
    },
    weightedScore: 0,
    priorityScore: 0,
    riskLevel: 'CRITICAL',
    sourceIp: srcIp,
    destinationIp: targetToCorrelate?.destinationIp || '10.0.4.15',
    asset,
    assetTier: 'Tier 0 - Crown Jewels',
    user,
    userRole: targetToCordonUserRole(user),
    device: `srv-${asset.toLowerCase()}`,
    timestamp: new Date().toISOString(),
    correlatedIncidentIds: [targetToCorrelate?.id].filter(Boolean) as string[],
    status: 'NEW',
    isNewAlert: true,
    recommendedActions: [
      'EMERGENCY LIVE ACTION: Quarantine asset immediately',
      'Execute firewall block for IP ' + srcIp,
      'Escalate to Tier 3 Lead Incident Commander',
    ],
  };
}

function targetToCordonUserRole(user: string): string {
  if (user.includes('admin')) return 'Enterprise Administrator';
  if (user.includes('fin')) return 'Finance Systems Principal';
  if (user.includes('miller')) return 'Chief of Medicine';
  return 'Privileged Operator';
}
